(set-logic LIA)
(echo "2 i0 = staticinvoke <test.Base64: int removeWhiteSpace(byte[])>(r0):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "3 $i1 = i0 % 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "4 if $i1 == 0 goto i2 = i0 / 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i1 Int))
(=> (= $i1 0) (= $i1 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i1 Int))
(=> (= $i1 0) (= $i1 0))))
(check-sat)
(pop)
(echo "8 i2 = i0 / 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "9 if i2 != 0 goto i56 = 0:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "12 i56 = 0:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int))
(=> (= i56 0) (= i56 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int))
(=> (= i56 0) (= i56 0))))
(check-sat)
(pop)
(echo "13 $i3 = i2 - 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i3 Int) (i2 Int))
(=> (= $i3 (+ i2 (- 1))) (= $i3 (+ i2 (- 1))))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) (i2 Int))
(=> (= $i3 (+ i2 (- 1))) (= $i3 (+ i2 (- 1))))))
(check-sat)
(pop)
(echo "14 i57 = $i3 * 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "15 $i4 = i2 - 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i3 Int) ($i4 Int) (i2 Int))
(=> (and (= $i3 (+ $i4 0)) (= $i3 (+ i2 (- 1)))) (and (= $i3 (+ $i4 0)) (= $i3 (+ i2 (- 1)))))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) ($i4 Int) (i2 Int))
(=> (and (= $i3 (+ $i4 0)) (= $i3 (+ i2 (- 1)))) (and (= $i3 (+ $i4 0)) (= $i3 (+ i2 (- 1)))))))
(check-sat)
(pop)
(echo "16 i58 = $i4 * 3:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "17 i59 = i57 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i57 Int) (i59 Int))
(=> (= i57 (+ i59 (- 1))) (= i57 (+ i59 (- 1))))))
(check-sat)
(pop)
(push)
(assert (forall ((i57 Int) (i59 Int))
(=> (= i57 (+ i59 (- 1))) (= i57 (+ i59 (- 1))))))
(check-sat)
(pop)
(echo "18 $b5 = r0[i57]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "19 b60 = $b5:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b5 Int) (b60 Int))
(=> (= $b5 (+ b60 0)) (= $b5 (+ b60 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b5 Int) (b60 Int))
(=> (= $b5 (+ b60 0)) (= $b5 (+ b60 0)))))
(check-sat)
(pop)
(echo "20 $z0 = staticinvoke <test.Base64: boolean isData(byte)>($b5):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "21 if $z0 == 0 goto $r1 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z0 Int))
(=> (= $z0 0) (= $z0 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z0 Int))
(=> (= $z0 0) (= $z0 0))))
(check-sat)
(pop)
(echo "22 i61 = i59 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i57 Int) (i59 Int) (i61 Int))
(=> (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2)))) (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2)))))))
(check-sat)
(pop)
(push)
(assert (forall ((i57 Int) (i59 Int) (i61 Int))
(=> (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2)))) (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2)))))))
(check-sat)
(pop)
(echo "23 $b6 = r0[i59]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "24 b62 = $b6:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b6 Int) (b62 Int))
(=> (= $b6 (+ b62 0)) (= $b6 (+ b62 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b6 Int) (b62 Int))
(=> (= $b6 (+ b62 0)) (= $b6 (+ b62 0)))))
(check-sat)
(pop)
(echo "25 $z1 = staticinvoke <test.Base64: boolean isData(byte)>($b6):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "26 if $z1 != 0 goto $r2 = <test.Base64: byte[] base64Alphabet>:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($z1 Int))
(=> (= $z1 0) (= $z1 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z1 Int))
(=> (= $z1 0) (= $z1 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "31 b63 = $r2[b60]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "33 b64 = $r3[b62]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "34 i65 = i61 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i57 Int) (i59 Int) (i61 Int) (i65 Int))
(=> (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2))) (= i57 (+ i65 (- 3)))) (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2))) (= i57 (+ i65 (- 3)))))))
(check-sat)
(pop)
(push)
(assert (forall ((i57 Int) (i59 Int) (i61 Int) (i65 Int))
(=> (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2))) (= i57 (+ i65 (- 3)))) (and (= i57 (+ i59 (- 1))) (= i57 (+ i61 (- 2))) (= i57 (+ i65 (- 3)))))))
(check-sat)
(pop)
(echo "35 b66 = r0[i61]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "36 b67 = r0[i65]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "37 $z2 = staticinvoke <test.Base64: boolean isData(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "38 if $z2 == 0 goto $z3 = staticinvoke <test.Base64: boolean isPad(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z2 Int))
(=> (= $z2 0) (= $z2 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z2 Int))
(=> (= $z2 0) (= $z2 0))))
(check-sat)
(pop)
(echo "39 $z11 = staticinvoke <test.Base64: boolean isData(byte)>(b67):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "40 if $z11 != 0 goto $i42 = i58 + 3:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($z11 Int))
(=> (= $z11 0) (= $z11 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z11 Int))
(=> (= $z11 0) (= $z11 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "41 $z3 = staticinvoke <test.Base64: boolean isPad(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "42 if $z3 == 0 goto $z4 = staticinvoke <test.Base64: boolean isPad(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z3 Int))
(=> (= $z3 0) (= $z3 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z3 Int))
(=> (= $z3 0) (= $z3 0))))
(check-sat)
(pop)
(echo "43 $z10 = staticinvoke <test.Base64: boolean isPad(byte)>(b67):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "44 if $z10 == 0 goto $z4 = staticinvoke <test.Base64: boolean isPad(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z10 Int))
(=> (= $z10 0) (= $z10 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z10 Int))
(=> (= $z10 0) (= $z10 0))))
(check-sat)
(pop)
(echo "45 $i36 = b64 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "46 if $i36 == 0 goto $i37 = i58 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i36 Int))
(=> (= $i36 0) (= $i36 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i36 Int))
(=> (= $i36 0) (= $i36 0))))
(check-sat)
(pop)
(echo "50 $i37 = i58 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i37 Int) (i58 Int))
(=> (= $i37 (+ i58 1)) (= $i37 (+ i58 1)))))
(check-sat)
(pop)
(push)
(assert (forall (($i37 Int) (i58 Int))
(=> (= $i37 (+ i58 1)) (= $i37 (+ i58 1)))))
(check-sat)
(pop)
(echo "52 $i39 = b63 << 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "53 $i38 = b64 >> 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "54 $i40 = $i39 | $i38:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "55 $b41 = (byte) $i40:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "58 $z4 = staticinvoke <test.Base64: boolean isPad(byte)>(b66):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "59 if $z4 != 0 goto $r4 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($z4 Int))
(=> (= $z4 0) (= $z4 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z4 Int))
(=> (= $z4 0) (= $z4 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "60 $z5 = staticinvoke <test.Base64: boolean isPad(byte)>(b67):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "61 if $z5 == 0 goto $r4 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z5 Int))
(=> (= $z5 0) (= $z5 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z5 Int))
(=> (= $z5 0) (= $z5 0))))
(check-sat)
(pop)
(echo "63 b68 = $r5[b66]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "64 $i7 = b68 & 3:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "65 if $i7 == 0 goto $i8 = i58 + 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i7 Int))
(=> (= $i7 0) (= $i7 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i7 Int))
(=> (= $i7 0) (= $i7 0))))
(check-sat)
(pop)
(echo "69 $i8 = i58 + 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i8 Int) (i58 Int))
(=> (= $i8 (+ i58 2)) (= $i8 (+ i58 2)))))
(check-sat)
(pop)
(push)
(assert (forall (($i8 Int) (i58 Int))
(=> (= $i8 (+ i58 2)) (= $i8 (+ i58 2)))))
(check-sat)
(pop)
(echo "71 i69 = i58 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i8 Int) (i58 Int) (i69 Int))
(=> (and (= $i8 (+ i58 2)) (= $i8 (+ i69 1))) (and (= $i8 (+ i58 2)) (= $i8 (+ i69 1))))))
(check-sat)
(pop)
(push)
(assert (forall (($i8 Int) (i58 Int) (i69 Int))
(=> (and (= $i8 (+ i58 2)) (= $i8 (+ i69 1))) (and (= $i8 (+ i58 2)) (= $i8 (+ i69 1))))))
(check-sat)
(pop)
(echo "72 $i10 = b63 << 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "73 $i9 = b64 >> 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "74 $i11 = $i10 | $i9:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "75 $b12 = (byte) $i11:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "77 $i13 = b64 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "78 $i16 = $i13 << 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "79 $i14 = b68 >> 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "80 $i15 = $i14 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "81 $i17 = $i16 | $i15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "82 $b18 = (byte) $i17:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "88 $i42 = i58 + 3:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i42 Int) (i58 Int))
(=> (= $i42 (+ i58 3)) (= $i42 (+ i58 3)))))
(check-sat)
(pop)
(push)
(assert (forall (($i42 Int) (i58 Int))
(=> (= $i42 (+ i58 3)) (= $i42 (+ i58 3)))))
(check-sat)
(pop)
(echo "91 b70 = $r12[b66]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "93 b71 = $r13[b67]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "94 i72 = i58 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i42 Int) (i58 Int) (i72 Int))
(=> (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2))) (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2))))))
(check-sat)
(pop)
(push)
(assert (forall (($i42 Int) (i58 Int) (i72 Int))
(=> (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2))) (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2))))))
(check-sat)
(pop)
(echo "95 $i44 = b63 << 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "96 $i43 = b64 >> 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "97 $i45 = $i44 | $i43:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "98 $b46 = (byte) $i45:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "100 i73 = i72 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i42 Int) (i58 Int) (i72 Int) (i73 Int))
(=> (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2)) (= $i42 (+ i73 1))) (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2)) (= $i42 (+ i73 1))))))
(check-sat)
(pop)
(push)
(assert (forall (($i42 Int) (i58 Int) (i72 Int) (i73 Int))
(=> (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2)) (= $i42 (+ i73 1))) (and (= $i42 (+ i58 3)) (= $i42 (+ i72 2)) (= $i42 (+ i73 1))))))
(check-sat)
(pop)
(echo "101 $i47 = b64 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "102 $i50 = $i47 << 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "103 $i48 = b70 >> 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "104 $i49 = $i48 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "105 $i51 = $i50 | $i49:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "106 $b52 = (byte) $i51:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "108 $i53 = b70 << 6:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "109 $i54 = $i53 | b71:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "110 $b55 = (byte) $i54:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "112 i74 = 0:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i74 Int))
(=> (= i74 0) (= i74 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i74 Int))
(=> (= i74 0) (= i74 0))))
(check-sat)
(pop)
(echo "113 i75 = 0:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i75 Int))
(=> (= i75 0) (= i75 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i75 Int))
(=> (= i75 0) (= i75 0))))
(check-sat)
(pop)
(echo "114 $i76 = i2 - 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int))
(=> (and (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1)))) (and (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1)))))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int))
(=> (and (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1)))) (and (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1)))))))
(check-sat)
(pop)
(echo "115 if i56 >= $i76 goto return r16:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int))
(=> (and (<= i56 (+ $i3 (- 1))) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)) (and (<= i56 (+ $i3 (- 1))) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int))
(=> (and (<= i56 (+ $i3 (- 1))) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)) (and (<= i56 (+ $i3 (- 1))) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int))
(=> (and (<= $i3 (+ i56 0)) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)) (and (<= $i3 (+ i56 0)) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int))
(=> (and (<= $i3 (+ i56 0)) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)) (and (<= $i3 (+ i56 0)) (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(echo "116 i77 = i75 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (>= i56 0)))))
(check-sat)
(pop)
(echo "117 $b19 = r0[i75]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "118 b78 = $b19:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b19 Int) (b78 Int))
(=> (= $b19 (+ b78 0)) (= $b19 (+ b78 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b19 Int) (b78 Int))
(=> (= $b19 (+ b78 0)) (= $b19 (+ b78 0)))))
(check-sat)
(pop)
(echo "119 $z6 = staticinvoke <test.Base64: boolean isData(byte)>($b19):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "120 if $z6 == 0 goto $r17 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z6 Int))
(=> (= $z6 0) (= $z6 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z6 Int))
(=> (= $z6 0) (= $z6 0))))
(check-sat)
(pop)
(echo "121 i79 = i77 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (>= i56 0)))))
(check-sat)
(pop)
(echo "122 $b20 = r0[i77]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "123 b80 = $b20:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b20 Int) (b80 Int))
(=> (= $b20 (+ b80 0)) (= $b20 (+ b80 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b20 Int) (b80 Int))
(=> (= $b20 (+ b80 0)) (= $b20 (+ b80 0)))))
(check-sat)
(pop)
(echo "124 $z7 = staticinvoke <test.Base64: boolean isData(byte)>($b20):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "125 if $z7 == 0 goto $r17 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z7 Int))
(=> (= $z7 0) (= $z7 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z7 Int))
(=> (= $z7 0) (= $z7 0))))
(check-sat)
(pop)
(echo "126 i81 = i79 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (= i75 (+ i81 (- 3))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (= i75 (+ i81 (- 3))) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (= i75 (+ i81 (- 3))) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 0)) (= i75 (+ i77 (- 1))) (= i75 (+ i79 (- 2))) (= i75 (+ i81 (- 3))) (>= i56 0)))))
(check-sat)
(pop)
(echo "127 $b21 = r0[i79]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "128 b82 = $b21:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b21 Int) (b82 Int))
(=> (= $b21 (+ b82 0)) (= $b21 (+ b82 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b21 Int) (b82 Int))
(=> (= $b21 (+ b82 0)) (= $b21 (+ b82 0)))))
(check-sat)
(pop)
(echo "129 $z8 = staticinvoke <test.Base64: boolean isData(byte)>($b21):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "130 if $z8 == 0 goto $r17 = new java.lang.Exception:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($z8 Int))
(=> (= $z8 0) (= $z8 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z8 Int))
(=> (= $z8 0) (= $z8 0))))
(check-sat)
(pop)
(echo "131 i75 = i81 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(echo "132 $b22 = r0[i81]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "133 b83 = $b22:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($b22 Int) (b83 Int))
(=> (= $b22 (+ b83 0)) (= $b22 (+ b83 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($b22 Int) (b83 Int))
(=> (= $b22 (+ b83 0)) (= $b22 (+ b83 0)))))
(check-sat)
(pop)
(echo "134 $z9 = staticinvoke <test.Base64: boolean isData(byte)>($b22):<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "135 if $z9 != 0 goto $r6 = <test.Base64: byte[] base64Alphabet>:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($z9 Int))
(=> (= $z9 0) (= $z9 0))))
(check-sat)
(pop)
(push)
(assert (forall (($z9 Int))
(=> (= $z9 0) (= $z9 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "140 b84 = $r6[b78]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "142 b85 = $r7[b80]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "144 b86 = $r8[b82]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "146 b87 = $r9[b83]:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "147 i88 = i74 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(echo "148 $i24 = b84 << 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "149 $i23 = b85 >> 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "150 $i25 = $i24 | $i23:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "151 $b26 = (byte) $i25:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "153 i89 = i88 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i74 (+ i89 (- 2))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i74 (+ i89 (- 2))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i74 (+ i89 (- 2))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 0)) (<= i74 (+ i75 (- 4))) (= i74 (+ i88 (- 1))) (= i74 (+ i89 (- 2))) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(echo "154 $i27 = b85 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "155 $i30 = $i27 << 4:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "156 $i28 = b86 >> 2:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "157 $i29 = $i28 & 15:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "158 $i31 = $i30 | $i29:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "159 $b32 = (byte) $i31:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "161 i74 = i89 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ i74 (- 3))) (<= i74 (+ i75 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 (- 3))) (<= i74 (+ i75 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ i74 (- 3))) (<= i74 (+ i75 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)) (and (<= i56 (+ i74 (- 3))) (<= i74 (+ i75 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 0)))))
(check-sat)
(pop)
(echo "162 $i33 = b86 << 6:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "163 $i34 = $i33 | b87:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "164 $b35 = (byte) $i34:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "166 i56 = i56 + 1:<test.Base64: byte[] decodeInternal(byte[])>")
(echo "fall through")
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ $i3 0)) (<= i56 (+ i74 (- 2))) (<= i74 (+ i75 (- 1))) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 1)) (and (<= i56 (+ $i3 0)) (<= i56 (+ i74 (- 2))) (<= i74 (+ i75 (- 1))) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 1)))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int) ($i4 Int) ($i76 Int) (i2 Int) (i56 Int) (i74 Int) (i75 Int) (i77 Int) (i79 Int) (i81 Int) (i88 Int) (i89 Int))
(=> (and (<= i56 (+ $i3 0)) (<= i56 (+ i74 (- 2))) (<= i74 (+ i75 (- 1))) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 1)) (and (<= i56 (+ $i3 0)) (<= i56 (+ i74 (- 2))) (<= i74 (+ i75 (- 1))) (= $i3 (+ $i4 0)) (= $i3 (+ $i76 0)) (= $i3 (+ i2 (- 1))) (= i74 (+ i88 2)) (= i74 (+ i89 1)) (= i75 (+ i77 3)) (= i75 (+ i79 2)) (= i75 (+ i81 1)) (>= i56 1)))))
(check-sat)
(pop)
