(set-logic LIA)
(echo "12 if $i0 != 6 goto virtualinvoke r1.<test.WBS: int update(int,boolean,boolean,int,int,int)>(i2, z0, z1, i3, i4, i5):<test.WBS: void main(java.lang.String[])>")
(echo "fall through")
(push)
(assert (forall (($i0 Int))
(=> (= $i0 6) (and (= $i0 6) (>= $i0 5)))))
(check-sat)
(pop)
(push)
(assert (forall (($i0 Int))
(=> (and (= $i0 6) (>= $i0 5)) (= $i0 6))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i0 Int))
(=> true (not (= $i0 6)))))
(check-sat)
(pop)
(push)
(assert (forall (($i0 Int))
(=> (not (= $i0 6)) true)))
(check-sat)
(pop)
