(set-logic LIA)
(echo "3 b0 = 1:<test.ConstantValuePropagation: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int))
(=> (= b0 1) (= b0 1))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int))
(=> (= b0 1) (= b0 1))))
(check-sat)
(pop)
(echo "4 b1 = 2:<test.ConstantValuePropagation: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b1 Int))
(=> (= b1 2) (and (< b1 5) (= b1 2) (>= b1 2)))))
(check-sat)
(pop)
(push)
(assert (forall ((b1 Int))
(=> (and (< b1 5) (= b1 2) (>= b1 2)) (= b1 2))))
(check-sat)
(pop)
(echo "5 i2 = b0 + b1:<test.ConstantValuePropagation: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int) (b1 Int) (i2 Int))
(=> (and (= b0 1) (= b1 2) (= i2 3)) (and (< b1 5) (< i2 5) (= b0 1) (= b1 2) (= i2 (+ b0 b1)) (>= b1 2) (>= i2 2)))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (b1 Int) (i2 Int))
(=> (and (< b1 5) (< i2 5) (= b0 1) (= b1 2) (= i2 (+ b0 b1)) (>= b1 2) (>= i2 2)) (and (= b0 1) (= b1 2) (= i2 3)))))
(check-sat)
(pop)
(echo "6 i4 = i2 + i3:<test.ConstantValuePropagation: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int) (b1 Int) (i2 Int) (i3 Int) (i4 Int))
(=> (and (= b0 1) (= b1 2) (= i2 3)) (and (< b1 5) (< i2 5) (= b0 1) (= b1 2) (= i2 (+ b0 b1)) (= i4 (+ i2 i3)) (>= b1 2) (>= i2 2)))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (b1 Int) (i2 Int) (i3 Int) (i4 Int))
(=> (and (< b1 5) (< i2 5) (= b0 1) (= b1 2) (= i2 (+ b0 b1)) (= i4 (+ i2 i3)) (>= b1 2) (>= i2 2)) (and (= b0 1) (= b1 2) (= i2 3)))))
(check-sat)
(pop)
