(set-logic LIA)
(echo "6 x = y:<test.BallonFactory: java.util.ArrayList getLines(java.awt.FontMetrics,java.lang.String,double,int)>")
(echo "fall through")
(push)
(assert (forall ((k Int)(v Int)(w Int)(x Int)(y Int))
(=> (and (<= v (+ y 0)) (<= x (+ y 0)) (<= w (+ k 0))) (and (<= v (+ y 0)) (<= k (+ w 0)) (<= x (+ w 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((k Int)(v Int)(w Int)(x Int)(y Int))
(=> (and (<= v (+ y 0)) (<= k (+ w 0)) (<= x (+ w 0))) (and (<= v (+ y 0)) (<= x (+ y 0)) (<= w (+ k 0))))))
(check-sat)
(pop)
