(set-logic LIA)
(echo "6 i1 = 0:<test.BallonFactory: java.util.ArrayList getLines(java.awt.FontMetrics,java.lang.String,double,int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int)(i2 Int))
(=> (= i1 0) (or (= i1 0) (>= i2 i1)))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int)(i2 Int))
(=> (or (= i1 0) (>= i2 i1)) (= i1 0))))
(check-sat)
(pop)
(echo "7 b2 = 2:<test.BallonFactory: java.util.ArrayList getLines(java.awt.FontMetrics,java.lang.String,double,int)>")
(echo "fall through")
(push)
(assert (forall ((b2 Int))
(=> (and (< b2 5) (> b2 0) (>= b2 2)) false)))
(check-sat)
(pop)
(push)
(assert (forall ((b2 Int))
(=> false (and (< b2 5) (> b2 0) (>= b2 2)))))
(check-sat)
(pop)
(echo "8 b3 = 0:<test.BallonFactory: java.util.ArrayList getLines(java.awt.FontMetrics,java.lang.String,double,int)>")
(echo "fall through")
(push)
(assert (forall ((b3 Int))
(=> (= b3 0) false)))
(check-sat)
(pop)
(push)
(assert (forall ((b3 Int))
(=> false (= b3 0))))
(check-sat)
(pop)
