(set-logic LIA)
(echo "6 i1 = 0:<test.BallonFactory: java.util.ArrayList getLines(java.awt.FontMetrics,java.lang.String,double,int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int))
(=> (= i1 0) (= i1 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int))
(=> (= i1 0) (= i1 0))))
(check-sat)
(pop)
