(set-logic LIA)
(echo "3 l2 = 0L:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l2 Int))
(=> (= l2 0) (= l2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((l2 Int))
(=> (= l2 0) (= l2 0))))
(check-sat)
(pop)
(echo "4 l3 = 1L:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l3 Int))
(=> (= l3 1) (> l3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((l3 Int))
(=> (> l3 0) (= l3 1))))
(check-sat)
(pop)
(echo "5 l4 = 0L:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l4 Int))
(=> (= l4 0) (= l4 0))))
(check-sat)
(pop)
(push)
(assert (forall ((l4 Int))
(=> (= l4 0) (= l4 0))))
(check-sat)
(pop)
(echo "6 l5 = 0L:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l5 Int))
(=> (= l5 0) (= l5 0))))
(check-sat)
(pop)
(push)
(assert (forall ((l5 Int))
(=> (= l5 0) (= l5 0))))
(check-sat)
(pop)
(echo "7 $b1 = l5 cmp l0:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "8 if $b1 >= 0 goto return l4:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (and (<= l5 (+ l0 (- 1))) (>= l5 0)) (and (> l0 0) (or (> l5 0) (= l5 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (and (> l0 0) (or (> l5 0) (= l5 0))) (and (<= l5 (+ l0 (- 1))) (>= l5 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (and (<= l0 (+ l5 0)) (>= l5 0)) (or (> l5 0) (= l5 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (or (> l5 0) (= l5 0)) (and (<= l0 (+ l5 0)) (>= l5 0)))))
(check-sat)
(pop)
(echo "9 l4 = l3 + l2:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l4 Int))
(=> (>= l4 1) (> l4 0))))
(check-sat)
(pop)
(push)
(assert (forall ((l4 Int))
(=> (> l4 0) (>= l4 1))))
(check-sat)
(pop)
(echo "10 l2 = l3:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l2 Int) (l3 Int))
(=> (and (>= l2 1) (= l2 (+ l3 0))) (and (> l2 0) (> l3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((l2 Int) (l3 Int))
(=> (and (> l2 0) (> l3 0)) (and (>= l2 1) (= l2 (+ l3 0))))))
(check-sat)
(pop)
(echo "11 l3 = l4:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l3 Int) (l4 Int))
(=> (and (= l3 (+ l4 0)) (>= l3 1)) (and (> l4 0) (> l3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((l3 Int) (l4 Int))
(=> (and (> l4 0) (> l3 0)) (and (= l3 (+ l4 0)) (>= l3 1)))))
(check-sat)
(pop)
(echo "12 l5 = l5 + 1L:<miniExample9: long example(long)>")
(echo "fall through")
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (and (<= l5 (+ l0 0)) (>= l5 1)) (and (> l5 0) (> l0 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((l0 Int) (l5 Int))
(=> (and (> l5 0) (> l0 0)) (and (<= l5 (+ l0 0)) (>= l5 1)))))
(check-sat)
(pop)
