(set-logic LIA)
(echo "7 i1 = i0:<miniExample8: void example(int,int,int,int,int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i1 Int))
(=> (= i0 (+ i1 0)) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i1 Int))
(=> true (= i0 (+ i1 0)))))
(check-sat)
(pop)
(echo "8 if i1 > i2 goto return:<miniExample8: void example(int,int,int,int,int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int))
(=> (and (<= i0 (+ i2 0)) (= i0 (+ i1 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int))
(=> true (and (<= i0 (+ i2 0)) (= i0 (+ i1 0))))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int))
(=> (and (<= i2 (+ i0 (- 1))) (= i0 (+ i1 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int))
(=> true (and (<= i2 (+ i0 (- 1))) (= i0 (+ i1 0))))))
(check-sat)
(pop)
(echo "9 if i3 > i4 goto return:<miniExample8: void example(int,int,int,int,int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> (<= i3 (+ i4 0)) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> true (<= i3 (+ i4 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> (<= i4 (+ i3 (- 1))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> true (<= i4 (+ i3 (- 1))))))
(check-sat)
(pop)
(echo "10 if i5 > i3 goto return:<miniExample8: void example(int,int,int,int,int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int)(i4 Int)(i5 Int))
(=> (and (<= i5 (+ i3 0)) (<= i3 (+ i4 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int)(i4 Int)(i5 Int))
(=> true (and (<= i5 (+ i3 0)) (<= i3 (+ i4 0))))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i3 Int)(i4 Int)(i5 Int))
(=> (and (<= i3 (+ i5 (- 1))) (<= i3 (+ i4 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int)(i4 Int)(i5 Int))
(=> true (and (<= i3 (+ i5 (- 1))) (<= i3 (+ i4 0))))))
(check-sat)
(pop)
(echo "11 if i1 > i3 goto return:<miniExample8: void example(int,int,int,int,int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int)(i3 Int)(i4 Int)(i5 Int))
(=> (and (<= i0 (+ i2 0)) (<= i5 (+ i3 0)) (<= i0 (+ i3 0)) (<= i3 (+ i4 0)) (= i0 (+ i1 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int)(i3 Int)(i4 Int)(i5 Int))
(=> true (and (<= i0 (+ i2 0)) (<= i5 (+ i3 0)) (<= i0 (+ i3 0)) (<= i3 (+ i4 0)) (= i0 (+ i1 0))))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int)(i3 Int)(i4 Int)(i5 Int))
(=> (and (<= i0 (+ i2 0)) (<= i5 (+ i3 0)) (<= i3 (+ i4 0)) (<= i3 (+ i0 (- 1))) (= i0 (+ i1 0))) true)))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i1 Int)(i2 Int)(i3 Int)(i4 Int)(i5 Int))
(=> true (and (<= i0 (+ i2 0)) (<= i5 (+ i3 0)) (<= i3 (+ i4 0)) (<= i3 (+ i0 (- 1))) (= i0 (+ i1 0))))))
(check-sat)
(pop)
