(set-logic LIA)
(echo "3 i2 = 0:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(echo "4 i3 = 0:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int))
(=> (= i3 0) (= i3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int))
(=> (= i3 0) (= i3 0))))
(check-sat)
(pop)
(echo "5 if i3 >= i0 goto return i2:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (<= i3 (+ i0 (- 1))) (>= i3 0)) (and (> i0 0) (or (= i3 0) (> i3 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (> i0 0) (or (= i3 0) (> i3 0))) (and (<= i3 (+ i0 (- 1))) (>= i3 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (<= i0 (+ i3 0)) (>= i3 0)) (and (or (< i0 0) (= i0 0) (> i0 0)) (or (= i3 0) (> i3 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (or (< i0 0) (= i0 0) (> i0 0)) (or (= i3 0) (> i3 0))) (and (<= i0 (+ i3 0)) (>= i3 0)))))
(check-sat)
(pop)
(echo "6 $i1 = i0 * i3:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall (($i1 Int))
(=> true (or (= $i1 0) (> $i1 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($i1 Int))
(=> (or (= $i1 0) (> $i1 0)) true)))
(check-sat)
(pop)
(echo "7 i2 = i2 + $i1:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> true (or (= i2 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (or (= i2 0) (> i2 0)) true)))
(check-sat)
(pop)
(echo "8 i3 = i3 + 1:<miniExample2: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (<= i3 (+ i0 0)) (>= i3 1)) (and (> i0 0) (> i3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i3 Int))
(=> (and (> i0 0) (> i3 0)) (and (<= i3 (+ i0 0)) (>= i3 1)))))
(check-sat)
(pop)
