(set-logic LIA)
(echo "3 b0 = 0:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int))
(=> (= b0 0) (= b0 0))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int))
(=> (= b0 0) (= b0 0))))
(check-sat)
(pop)
(echo "4 if b0 >= i1 goto $r0 = <java.lang.System: java.io.PrintStream err>:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int) (i1 Int))
(=> (and (= b0 0) (>= i1 1)) (and (= b0 0) (> i1 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (i1 Int))
(=> (and (= b0 0) (> i1 0)) (and (= b0 0) (>= i1 1)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((b0 Int) (i1 Int))
(=> (and (<= i1 0) (= b0 0)) (and (= b0 0) (or (< i1 0) (= i1 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (i1 Int))
(=> (and (= b0 0) (or (< i1 0) (= i1 0))) (and (<= i1 0) (= b0 0)))))
(check-sat)
(pop)
(echo "10 i2 = 0:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(echo "11 if i2 >= i1 goto return:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (<= i2 (+ i1 (- 1))) (>= i2 0)) (and (> i1 0) (or (= i2 0) (> i2 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (> i1 0) (or (= i2 0) (> i2 0))) (and (<= i2 (+ i1 (- 1))) (>= i2 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (<= i1 (+ i2 0)) (>= i2 0)) (or (= i2 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (or (= i2 0) (> i2 0)) (and (<= i1 (+ i2 0)) (>= i2 0)))))
(check-sat)
(pop)
(echo "12 if b0 != i2 goto $r1 = <java.lang.System: java.io.PrintStream err>:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((b0 Int) (i2 Int))
(=> (and (= b0 0) (= i2 0)) (and (= b0 0) (= i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (i2 Int))
(=> (and (= b0 0) (= i2 0)) (and (= b0 0) (= i2 0)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((b0 Int) (i1 Int) (i2 Int))
(=> (and (<= i2 (+ i1 (- 1))) (= b0 0) (>= i2 0)) (and (= b0 0) (> i1 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((b0 Int) (i1 Int) (i2 Int))
(=> (and (= b0 0) (> i1 0) (> i2 0)) (and (<= i2 (+ i1 (- 1))) (= b0 0) (>= i2 0)))))
(check-sat)
(pop)
(echo "17 i2 = i2 + 1:<miniExample7: void example(int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (<= i2 (+ i1 0)) (>= i2 1)) (and (> i1 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (> i1 0) (> i2 0)) (and (<= i2 (+ i1 0)) (>= i2 1)))))
(check-sat)
(pop)
