(set-logic LIA)
(echo "3 if i0 < 0 goto $r0 = new java.lang.RuntimeException:<miniExample5: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int))
(=> (>= i0 0) (or (> i0 0) (= i0 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int))
(=> (or (> i0 0) (= i0 0)) (>= i0 0))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int))
(=> (<= i0 (- 1)) (< i0 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int))
(=> (< i0 0) (<= i0 (- 1)))))
(check-sat)
(pop)
(echo "4 i2 = 0:<miniExample5: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(echo "5 if i2 >= i0 goto $i1 = i2 - i0:<miniExample5: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (>= i2 0) (<= i2 (+ i0 (- 1)))) (and (> i0 0) (or (= i2 0) (> i2 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (> i0 0) (or (= i2 0) (> i2 0))) (and (>= i2 0) (<= i2 (+ i0 (- 1)))))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (>= i0 0) (= i0 (+ i2 0))) (and (or (> i0 0) (= i0 0)) (or (= i2 0) (> i2 0))))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (or (> i0 0) (= i0 0)) (or (= i2 0) (> i2 0))) (and (>= i0 0) (= i0 (+ i2 0))))))
(check-sat)
(pop)
(echo "6 i2 = i2 + 1:<miniExample5: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (>= i2 1) (<= i2 (+ i0 0))) (and (> i0 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i2 Int))
(=> (and (> i0 0) (> i2 0)) (and (>= i2 1) (<= i2 (+ i0 0))))))
(check-sat)
(pop)
(echo "8 $i1 = i2 - i0:<miniExample5: int example(int)>")
(echo "fall through")
(push)
(assert (forall (($i1 Int))
(=> true (or (= $i1 0) (> $i1 0)))))
(check-sat)
(pop)
(push)
(assert (forall (($i1 Int))
(=> (or (= $i1 0) (> $i1 0)) true)))
(check-sat)
(pop)
