(set-logic LIA)
(echo "2 i1 = 0:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (forall ((i1 Int))
(=> (= i1 0) (= i1 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int))
(=> (= i1 0) (= i1 0))))
(check-sat)
(pop)
(echo "3 i2 = 1:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 1) (> i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (> i2 0) (= i2 1))))
(check-sat)
(pop)
(echo "4 $i3 = virtualinvoke r0.<miniExample6: int random()>():<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "5 if 1 != $i3 goto return:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (forall (($i3 Int))
(=> (= $i3 1) (> $i3 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i3 Int))
(=> (> $i3 0) (= $i3 1))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "6 if i1 != i2 goto $i3 = virtualinvoke r0.<miniExample6: int random()>():<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (= i1 0) (= i2 1)) (and (= i1 0) (> i2 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int) (i2 Int))
(=> (and (= i1 0) (> i2 0)) (and (= i1 0) (= i2 1)))))
(check-sat)
(pop)
(echo "7 $i0 = virtualinvoke r0.<miniExample6: int random()>():<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
(echo "8 if 1 != $i0 goto i1 = i2 + 1:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
(echo "9 i2 = i1 + 1:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
(echo "11 i1 = i2 + 1:<miniExample6: void example()>")
(echo "fall through")
(push)
(assert (=> false false))
(check-sat)
(pop)
(push)
(assert (=> false false))
(check-sat)
(pop)
