(set-logic LIA)
(echo "3 i3 = 0:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int))
(=> (= i3 0) (= i3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int))
(=> (= i3 0) (= i3 0))))
(check-sat)
(pop)
(echo "4 i4 = 1:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i4 Int))
(=> (= i4 1) (> i4 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i4 Int))
(=> (> i4 0) (= i4 1))))
(check-sat)
(pop)
(echo "5 i5 = 1:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i5 Int))
(=> (= i5 1) (> i5 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i5 Int))
(=> (> i5 0) (= i5 1))))
(check-sat)
(pop)
(echo "6 i6 = 3:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i6 Int))
(=> (= i6 3) (> i6 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i6 Int))
(=> (> i6 0) (= i6 3))))
(check-sat)
(pop)
(echo "7 if i6 >= i0 goto return i5:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (<= i6 (+ i0 (- 1))) (>= i6 3)) (and (> i0 0) (> i6 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (> i0 0) (> i6 0)) (and (<= i6 (+ i0 (- 1))) (>= i6 3)))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (>= i6 3) (<= i0 (+ i6 0))) (and (or (> i0 0) (= i0 0) (< i0 0)) (> i6 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (or (> i0 0) (= i0 0) (< i0 0)) (> i6 0)) (and (>= i6 3) (<= i0 (+ i6 0))))))
(check-sat)
(pop)
(echo "8 $i1 = i5 + i4:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall (($i1 Int))
(=> (>= $i1 2) (> $i1 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i1 Int))
(=> (> $i1 0) (>= $i1 2))))
(check-sat)
(pop)
(echo "9 i2 = $i1 + i3:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (>= i2 2) (> i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (> i2 0) (>= i2 2))))
(check-sat)
(pop)
(echo "10 i3 = i4:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> (and (>= i3 1) (= i3 (+ i4 0))) (and (> i4 0) (> i3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int)(i4 Int))
(=> (and (> i4 0) (> i3 0)) (and (>= i3 1) (= i3 (+ i4 0))))))
(check-sat)
(pop)
(echo "11 i4 = i5:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i4 Int)(i5 Int))
(=> (and (>= i4 1) (= i4 (+ i5 0))) (and (> i4 0) (> i5 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i4 Int)(i5 Int))
(=> (and (> i4 0) (> i5 0)) (and (>= i4 1) (= i4 (+ i5 0))))))
(check-sat)
(pop)
(echo "12 i5 = i2:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int)(i5 Int))
(=> (and (>= i2 2) (= i2 (+ i5 0))) (and (> i2 0) (> i5 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int)(i5 Int))
(=> (and (> i2 0) (> i5 0)) (and (>= i2 2) (= i2 (+ i5 0))))))
(check-sat)
(pop)
(echo "13 i6 = i6 + 1:<miniExample3: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (<= i6 (+ i0 0)) (>= i6 4)) (and (> i0 0) (> i6 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int)(i6 Int))
(=> (and (> i0 0) (> i6 0)) (and (<= i6 (+ i0 0)) (>= i6 4)))))
(check-sat)
(pop)
