(set-logic LIA)
(echo "3 i2 = 0:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int))
(=> (= i2 0) (= i2 0))))
(check-sat)
(pop)
(echo "4 i3 = 1:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i3 Int))
(=> (= i3 1) (> i3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i3 Int))
(=> (> i3 0) (= i3 1))))
(check-sat)
(pop)
(echo "5 i4 = 2:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i4 Int))
(=> (= i4 2) (> i4 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i4 Int))
(=> (> i4 0) (= i4 2))))
(check-sat)
(pop)
(echo "6 if i4 >= i0 goto return i3:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (and (>= i4 2) (<= i4 (+ i0 (- 1)))) (and (> i0 0) (> i4 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (and (> i0 0) (> i4 0)) (and (>= i4 2) (<= i4 (+ i0 (- 1)))))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (and (>= i4 2) (<= i0 (+ i4 0))) (> i4 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (> i4 0) (and (>= i4 2) (<= i0 (+ i4 0))))))
(check-sat)
(pop)
(echo "7 i1 = i2 + i3:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int))
(=> (>= i1 1) (> i1 0))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int))
(=> (> i1 0) (>= i1 1))))
(check-sat)
(pop)
(echo "8 i2 = i3:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i2 Int) (i3 Int))
(=> (and (= i2 (+ i3 0)) (>= i2 1)) (and (> i2 0) (> i3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i2 Int) (i3 Int))
(=> (and (> i2 0) (> i3 0)) (and (= i2 (+ i3 0)) (>= i2 1)))))
(check-sat)
(pop)
(echo "9 i3 = i1:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i1 Int) (i3 Int))
(=> (and (= i1 (+ i3 0)) (>= i1 1)) (and (> i1 0) (> i3 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i1 Int) (i3 Int))
(=> (and (> i1 0) (> i3 0)) (and (= i1 (+ i3 0)) (>= i1 1)))))
(check-sat)
(pop)
(echo "10 i4 = i4 + 1:<miniExample4: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (and (>= i4 3) (<= i4 (+ i0 0))) (and (> i0 0) (> i4 0)))))
(check-sat)
(pop)
(push)
(assert (forall ((i0 Int) (i4 Int))
(=> (and (> i0 0) (> i4 0)) (and (>= i4 3) (<= i4 (+ i0 0))))))
(check-sat)
(pop)
