(set-logic LIA)
(echo "3 i1 = neg i0:<miniExample1: int example(int)>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "4 $i2 = i0 - i1:<miniExample1: int example(int)>")
(echo "fall through")
(push)
(assert (=> true true))
(check-sat)
(pop)
(push)
(assert (=> true true))
(check-sat)
(pop)
(echo "5 if 120 <= $i2 goto b3 = -1:<miniExample1: int example(int)>")
(echo "fall through")
(push)
(assert (forall (($i2 Int))
(=> (<= $i2 119) true)))
(check-sat)
(pop)
(push)
(assert (forall (($i2 Int))
(=> true (<= $i2 119))))
(check-sat)
(pop)
(echo "branch out")
(push)
(assert (forall (($i2 Int))
(=> (>= $i2 120) (> $i2 0))))
(check-sat)
(pop)
(push)
(assert (forall (($i2 Int))
(=> (> $i2 0) (>= $i2 120))))
(check-sat)
(pop)
(echo "6 b3 = 1:<miniExample1: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b3 Int))
(=> (= b3 1) (> b3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((b3 Int))
(=> (> b3 0) (= b3 1))))
(check-sat)
(pop)
(echo "8 b3 = -1:<miniExample1: int example(int)>")
(echo "fall through")
(push)
(assert (forall ((b3 Int))
(=> (= b3 (- 1)) (< b3 0))))
(check-sat)
(pop)
(push)
(assert (forall ((b3 Int))
(=> (< b3 0) (= b3 (- 1)))))
(check-sat)
(pop)
