package processing.smt;

import java.util.Optional;
import java.util.Set;
import java.util.function.BinaryOperator;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import soot.Local;
import common.Locals;

public class SmtExpressionFixpointTest {

    @ParameterizedTest
    @MethodSource("smtConnectedFixpointProvider")
    void testConnectedFixpointUnion(String left,
                                    String right,
                                    Set<Local> changedVariables,
                                    Set<Local> expectedVariables,
                                    Optional<String> leftProjection,
                                    Optional<String> rightProjection) {
        SmtExpression leftExpr = SmtExpressionReader.parse(left);
        SmtExpression rightExpr = SmtExpressionReader.parse(right);
        Set<Local> projectedVariables = SmtExpression.connectedUnion(changedVariables, leftExpr, rightExpr);
        assertAll(() -> assertEquals(expectedVariables, projectedVariables),
                  () -> assertEquals(leftProjection,
                                     leftExpr.toSmt2(projectedVariables)),
                  () -> assertEquals(rightProjection,
                                     rightExpr.toSmt2(projectedVariables)));
    }

    @ParameterizedTest
    @MethodSource("smtReachableFixpointProvider")
    void testReachableFixpointUnion(String left,
                                    String right,
                                    Set<Local> changedVariables,
                                    Set<Local> expectedVariables,
                                    Optional<String> leftProjection,
                                    Optional<String> rightProjection) {
        SmtExpression leftExpr = SmtExpressionReader.parse(left);
        SmtExpression rightExpr = SmtExpressionReader.parse(right);
        Set<Local> projectedVariables = SmtExpression.reachableUnion(changedVariables, leftExpr, rightExpr);
        assertAll(() -> assertEquals(expectedVariables, projectedVariables),
                  () -> assertEquals(leftProjection,
                                     leftExpr.toSmt2(projectedVariables)),
                  () -> assertEquals(rightProjection,
                                     rightExpr.toSmt2(projectedVariables)));
    }

    private static Stream<Arguments> smtConnectedFixpointProvider() {
        return Stream.of(Stream.of(Arguments.arguments("(<= x (+ y 3))",
                                                       "(and (<= k (+ y 0)) (<= x (+ y 3)))",
                                                       Set.of(Locals.get("x")),
                                                       Locals.get("x", "y", "k"),
                                                       Optional.of("(<= x (+ y 3))"),
                                                       Optional.of("(and (<= k (+ y 0)) (<= x (+ y 3)))"))),
                         Stream.of(Arguments.arguments("(and (<= x (+ y 3)))",
                                                       "(and (<= k (+ y 0)) (<= x (+ y 3)))",
                                                       Locals.get("x", "y"),
                                                       Locals.get("k", "x", "y"),
                                                       Optional.of("(<= x (+ y 3))"),
                                                       Optional.of("(and (<= k (+ y 0)) (<= x (+ y 3)))"))),
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c", "d", "e"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ b 2))",
                                                                             "(<= d (+ e 3)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Locals.get("a", "b"),
                                                       Locals.get("a", "b", "c", "d", "e"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ b 2))",
                                                                             "(<= d (+ e 3)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3))",
                                                                 "(<= f (+ d 4)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c", "d", "e", "f"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ b 2))",
                                                                             "(<= d (+ e 3))",
                                                                             "(<= f (+ d 4)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ e 2)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c", "d", "e"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ b 2))",
                                                                             "(<= d (+ e 3)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ e 2)))").collect(Collectors.joining(" ")))))
                         ).flatMap(s -> s.map(v -> v));
    }

    private static Stream<Arguments> smtReachableFixpointProvider() {
        return Stream.of(// 1
                         Stream.of(Arguments.arguments("(<= x (+ y 3))",
                                                       "(and (<= k (+ y 0)) (<= x (+ y 3)))",
                                                       Set.of(Locals.get("x")),
                                                       Locals.get("x", "y"),
                                                       Optional.of("(<= x (+ y 3))"),
                                                       Optional.of("(<= x (+ y 3))"))),
                         // 2
                         Stream.of(Arguments.arguments("(and (<= x (+ y 3)))",
                                                       "(and (<= k (+ y 0)) (<= x (+ y 3)))",
                                                       Locals.get("x", "y"),
                                                       Locals.get("k", "x", "y"),
                                                       Optional.of("(<= x (+ y 3))"),
                                                       Optional.of("(and (<= k (+ y 0)) (<= x (+ y 3)))"))),
                         // 3
                         Stream.of(Arguments.arguments(Stream.of("(and (<= b (+ a 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= e (+ d 2))",
                                                                 "(<= d (+ g 3))",
                                                                 "(<= f (+ d 4)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ e 0))",
                                                                 "(<= b (+ a 1))",
                                                                 "(<= c (+ b 2))",
                                                                 "(<= d (+ g 3))",
                                                                 "(<= g (+ f 4)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("b")),
                                                       Locals.get("a", "b", "c", "d", "e", "f", "g"),
                                                       Optional.of(Stream.of("(and (<= b (+ a 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ g 3))",
                                                                             "(<= e (+ d 2))",
                                                                             "(<= f (+ d 4)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ e 0))",
                                                                             "(<= b (+ a 1))",
                                                                             "(<= c (+ b 2))",
                                                                             "(<= d (+ g 3))",
                                                                             "(<= g (+ f 4)))").collect(Collectors.joining(" "))))),
                         // 4
                         Stream.of(Arguments.arguments(Stream.of("(and (<= b (+ a 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= e (+ d 2))",
                                                                 "(<= d (+ g 3))",
                                                                 "(<= f (+ d 4)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ e 0))",
                                                                 "(<= b (+ a 1))",
                                                                 "(<= c (+ b 2))",
                                                                 "(<= d (+ g 3))",
                                                                 "(<= f (+ g 4)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("b")),
                                                       Locals.get("a", "b", "c", "d", "e", "g", "f"),
                                                       Optional.of(Stream.of("(and (<= b (+ a 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ g 3))",
                                                                             "(<= e (+ d 2))",
                                                                             "(<= f (+ d 4)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ e 0))",
                                                                             "(<= b (+ a 1))",
                                                                             "(<= c (+ b 2))",
                                                                             "(<= d (+ g 3))",
                                                                             "(<= f (+ g 4)))").collect(Collectors.joining(" "))))),
                         // 5
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         // 6
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Locals.get("a", "b"),
                                                       Locals.get("a", "b", "c", "d"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ b 2)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         // 7
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3))",
                                                                 "(<= f (+ d 4)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         // 8
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ b 2))",
                                                                 "(<= d (+ e 3)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ e 2)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1)))").collect(Collectors.joining(" "))))),
                         // 9
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= d (+ c 1))",
                                                                 "(<= f (+ d 2)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b (+ c 1))",
                                                                 "(<= d (+ e 2)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("a")),
                                                       Locals.get("a", "b", "c", "d", "e", "f"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= d (+ c 1))",
                                                                             "(<= f (+ d 2)))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b (+ c 1))",
                                                                             "(<= d (+ e 2)))").collect(Collectors.joining(" "))))),
                         // 10
                         Stream.of(Arguments.arguments(Stream.of("(and (<= a (+ b 0))",
                                                                 "(<= b 3)",
                                                                 "(>= b 0))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (<= a (+ b 2))",
                                                                 "(<= b 4)",
                                                                 "(>= b (- 1)))").collect(Collectors.joining(" ")),
                                                       Set.of(Locals.get("b")),
                                                       Locals.get("a", "b"),
                                                       Optional.of(Stream.of("(and (<= a (+ b 0))",
                                                                             "(<= b 3)",
                                                                             "(>= b 0))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= a (+ b 2))",
                                                                             "(<= b 4)",
                                                                             "(>= b (- 1)))").collect(Collectors.joining(" "))))),
                         // 11 - base64_17:147
                         Stream.of(Arguments.arguments(Stream.of("(and (= $i1 0)",
                                                                 "(>= i56 0)",
                                                                 "(= $b19 (+ b78 0))",
                                                                 "(= $b20 (+ b80 0))",
                                                                 "(= $b21 (+ b82 0))",
                                                                 "(= $b22 (+ b83 0))",
                                                                 "(= $b5 (+ b60 0))",
                                                                 "(= $b6 (+ b62 0))",
                                                                 "(= $i3 (+ $i4 0))",
                                                                 "(= $i3 (+ $i76 0))",
                                                                 "(= $i3 (+ i2 (- 1)))",
                                                                 "(<= i56 (+ $i3 (- 1)))",
                                                                 "(<= i56 (+ i74 0))",
                                                                 "(= i57 (+ i59 (- 1)))",
                                                                 "(= i57 (+ i61 (- 2)))",
                                                                 "(= i57 (+ i65 (- 3)))",
                                                                 "(<= i74 (+ i75 (- 4)))",
                                                                 "(= i74 (+ i88 (- 1)))",
                                                                 "(= i75 (+ i77 3))",
                                                                 "(= i75 (+ i79 2))",
                                                                 "(= i75 (+ i81 1)))").collect(Collectors.joining(" ")),
                                                       Stream.of("(and (= $i1 0)",
                                                                 "(>= i56 0)",
                                                                 "(= $b19 (+ b78 0))",
                                                                 "(= $b20 (+ b80 0))",
                                                                 "(= $b21 (+ b82 0))",
                                                                 "(= $b22 (+ b83 0))",
                                                                 "(= $b5 (+ b60 0))",
                                                                 "(= $b6 (+ b62 0))",
                                                                 "(= $i3 (+ $i4 0))",
                                                                 "(= $i3 (+ $i76 0))",
                                                                 "(= $i3 (+ i2 (- 1)))",
                                                                 "(<= i56 (+ $i3 (- 1)))",
                                                                 "(<= i56 (+ i74 0))",
                                                                 "(= i57 (+ i59 (- 1)))",
                                                                 "(= i57 (+ i61 (- 2)))",
                                                                 "(= i57 (+ i65 (- 3)))",
                                                                 "(<= i74 (+ i75 (- 4)))",
                                                                 "(= i74 (+ i88 (- 1)))",
                                                                 "(= i75 (+ i77 3))",
                                                                 "(= i75 (+ i79 2))",
                                                                 "(= i75 (+ i81 1)))").collect(Collectors.joining(" ")),
                                                       Locals.get("i74", "i88"),
                                                       Locals.get("i56", "i74", "i75", "i77", "i79", "i81", "i88"),
                                                       Optional.of(Stream.of("(and (<= i56 (+ i74 0))",
                                                                             "(<= i74 (+ i75 (- 4)))",
                                                                             "(= i74 (+ i88 (- 1)))",
                                                                             "(= i75 (+ i77 3))",
                                                                             "(= i75 (+ i79 2))",
                                                                             "(= i75 (+ i81 1))",
                                                                             "(>= i56 0))").collect(Collectors.joining(" "))),
                                                       Optional.of(Stream.of("(and (<= i56 (+ i74 0))",
                                                                             "(<= i74 (+ i75 (- 4)))",
                                                                             "(= i74 (+ i88 (- 1)))",
                                                                             "(= i75 (+ i77 3))",
                                                                             "(= i75 (+ i79 2))",
                                                                             "(= i75 (+ i81 1))",
                                                                             "(>= i56 0))").collect(Collectors.joining(" ")))))
                         ).flatMap(s -> s.map(v -> v));
    }
}
